---
name: Build and push container image
# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      version_tag:
        description: "The version tag to build and push (e.g. v1.2.3 or latest)"
        required: true
        default: "latest"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: "recursive"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v3.6.0
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Determine Docker Tag
        id: docker_tag
        run: |
          if  [[ "${{github.event_name}}" == 'push' ]]; then
            tag="${{ github.ref_name }}"
          else
            tag="${{ github.event.inputs.version_tag }}"
          fi
          echo "docker_tag=$tag" >> $GITHUB_OUTPUT

      - name: Build and push waldiez/studio
        uses: docker/build-push-action@v6.18.0
        with:
          platforms: |
            linux/amd64
            linux/arm64
          file: Containerfile
          context: .
          push: true
          tags: |
            waldiez/studio:${{ steps.docker_tag.outputs.docker_tag }}
            quay.io/waldiez/studio:${{ steps.docker_tag.outputs.docker_tag }}
